# name: Build and Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Other build steps here

#       - name: Deploy to GitHub Pages
#         run: |
#           sh push.sh "auto-commit"
#           git config --global user.name 'github-actions[bot]'
#           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
#           # git add .
#           # git commit -m "auto-commit"
#           # git push
#         env:
#           GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}


name: Generate personal website
on: 
  push:
  schedule:
      - cron: '0 0 * * *' # Once per day at midnight
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: pip install --upgrade pip
    - run: pip install -rrequirements.txt
    # - run: python generate.py
    - run: git config --global user.email "coendevente@gmail.com"
    - run: git config --global user.name "coendevente"
    - name: Deploy to GitHub Pages
      run: sh push.sh "auto-commit"
      # run: |
      #   git pull
      #   python3 generate.py
      #   cd site
      #   git add -u
      #   git commit -m "auto-commit"
      #   git push origin HEAD:main
      #   cd ..
      #   git add -u
      #   git add site
      #   git commit -m "auto-commit"
      #   git push --recurse-submodules=on-demand origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      uses: stefanzweifel/git-auto-commit-action@v4
    # - run: |
    #     cd site
    #     git config user.email "coendevente@gmail.com"
    #     git config user.name "coendevente"
    #     git add --all
    #     git commit -m "Update submodules" || echo "No changes to commit"
    #     git push --recurse-submodules=check origin HEAD:master
    #     cd ..
    # - run: |
    #     git config user.email "coendevente@gmail.com"
    #     git config user.name "coendevente"
    #     git add --all
    #     git commit -m "Update submodules" || echo "No changes to commit"
    #     git push --recurse-submodules=check
    
